sudo: false

dist: focal

language: python

matrix:
  include:
    - python: "2.7"
    - python: "3.4"
      dist: xenial
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "3.10-dev"
    - python: "pypy2"
    - python: "pypy3"
  allow_failures:
    - python: "3.10-dev"

cache:
  directories:
    - octane-mock
  pip: true

env:
  global:
    # If changing this number, please also change it in `tests/conftest.py`.
    - OCTANE_MOCK_VERSION=1.0.0

before_install:
  # Unpack and start octane-mock so that the test suite can talk to it
  - |
    if [ ! -d "octane-mock/octane-mock_${OCTANE_MOCK_VERSION}" ]; then
      mkdir -p octane-mock/octane-mock_${OCTANE_MOCK_VERSION}/
      curl -L "https://github.com/octane/octane-mock/releases/download/v${OCTANE_MOCK_VERSION}/octane-mock_${OCTANE_MOCK_VERSION}_linux_amd64.tar.gz" -o "octane-mock/octane-mock_${OCTANE_MOCK_VERSION}_linux_amd64.tar.gz"
      tar -zxf "octane-mock/octane-mock_${OCTANE_MOCK_VERSION}_linux_amd64.tar.gz" -C "octane-mock/octane-mock_${OCTANE_MOCK_VERSION}/"
    fi
  - |
    octane-mock/octane-mock_${OCTANE_MOCK_VERSION}/octane-mock > /dev/null &
    OCTANE_MOCK_PID=$!
  - export PATH="${PATH}:${PWD}/octane-mock/octane-mock_${OCTANE_MOCK_VERSION}"

install:
  - pip install --upgrade pip virtualenv
  - make venv

script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then make lint; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.9' ]]; then make fmtcheck; fi
  - make test-travis

after_success: make coveralls
